###########################
# Shorthands Dictionaries #
###########################


shorthand_properties = {
    "@bg": "background-color",
    "@c": "color",
    "@fs": "font-size",
    "@ff": "font-family",
    "@fw": "font-weight",
    "@lh": "line-height",
    "@m": "margin",
    "@mt": "margin-top",
    "@mr": "margin-right",
    "@mb": "margin-bottom",
    "@ml": "margin-left",
    "@p": "padding",
    "@pt": "padding-top",
    "@pr": "padding-right",
    "@pb": "padding-bottom",
    "@pl": "padding-left",
    "@w": "width",
    "@h": "height",
    "@br": "border-radius",
    "@bc": "border-color",
    "@bs": "border-style",
    "@bw": "border-width",
    "@d": "display",
    "@jc": "justify-content",
    "@flx": "flex",
    "@fld": "flex-direction",
    "@flw": "flex-wrap",
    "@flg": "flex-grow",
    "@fls": "flex-shrink",
    "@flb": "flex-basis",
    "@ai": "align-items",
    "@ac": "align-content",
    "@as": "align-self",
    "@fl": "float",
    "@pos": "position",
    "@t": "top",
    "@r": "right",
    "@b": "bottom",
    "@l": "left",
    "@z": "z-index",
    "@op": "opacity",
    "@o": "outline",
    "@ov": "overflow",
    "@ta": "text-align",
    "@td": "text-decoration",
    "@ti": "text-indent",
    "@tt": "text-transform",
    "@va": "vertical-align",
    "@whs": "white-space",
    "@ws": "word-spacing",
    "@v": "visibility",
    "@lst": "list-style-type",
    "@ls": "letter-spacing",
    "@bgp": "background-position",
    "@bgr": "background-repeat",
    "@bgs": "background-size",
    "@bgimg": "background-image",
    "@tsh": "text-shadow",
    "@bxsh": "box-shadow",
    "@tr": "transition",
    "@bo": "border",
    "@cur": "cursor",
    "@cp": "clip-path",
    "@f": "filter",
    "@mo": "mix-blend-mode",
    "@bgbl": "background-blur",
    "@blur": "blur",
    "@ct": "content",
    "@cl": "clear",
    "@cs": "counter-reset",
    "@ci": "counter-increment",
    "@q": "quotes",
    "@rfs": "resize",
    "@tbl": "table-layout",
    "@boc": "box-sizing",
    "@olw": "outline-width",
    "@ols": "outline-style",
    "@olc": "outline-color",
    "@objf": "object-fit",
    "@objp": "object-position",
    "@anim": "animation",
    "@animn": "animation-name",
    "@animd": "animation-duration",
    "@animtf": "animation-timing-function",
    "@animdly": "animation-delay",
    "@animic": "animation-iteration-count",
    "@animdir": "animation-direction",
    "@animfd": "animation-fill-mode",
    "@animps": "animation-play-state",
    "@tf": "transform",
    "@tfor": "transform-origin",
    "@tfbx": "transform-box",
    "@per": "perspective",
    "@pero": "perspective-origin",
    "@bkf": "backface-visibility",
    "@gr": "grid",
    "@grt": "grid-template",
    "@grtc": "grid-template-columns",
    "@grtr": "grid-template-rows",
    "@gra": "grid-area",
    "@grr": "grid-row",
    "@grc": "grid-column",
    "@grs": "grid-row-start",
    "@gre": "grid-row-end",
    "@gcs": "grid-column-start",
    "@gce": "grid-column-end",
    "@gga": "grid-gap",
    "@ggt": "grid-template",
    "@ggtar": "grid-template-areas",
    "@gauto": "grid-auto",
    "@gautoe": "grid-auto-rows",
    "@gautoc": "grid-auto-columns",
    "@gautof": "grid-auto-flow",
    "@bdci": "border-image",
    "@bdcis": "border-image-source",
    "@bdcisl": "border-image-slice",
    "@bdcsw": "border-image-width",
    "@bdcso": "border-image-outset",
    "@bdcir": "border-image-repeat",
    "@maxw": "max-width",
    "@maxh": "max-height",
    "@minw": "min-width",
    "@minh": "min-height",
    "@orph": "orphans",
    "@wid": "widows",
    "@wsb": "word-break",
    "@wsh": "word-wrap",
    "@oloff": "outline-offset",
    "@col": "columns",
    "@colw": "column-width",
    "@colc": "column-count",
    "@colg": "column-gap",
    "@colr": "column-rule",
    "@colrs": "column-rule-style",
    "@colrw": "column-rule-width",
    "@colrc": "column-rule-color",
    "@colsp": "column-span",
    "@rot": "rotate",
    "@scal": "scale",
    "@skw": "skew",
    "@tran": "translate",
    "@uc": "unicode-bidi",
    "@wr": "writing-mode",
    "@tdir": "text-direction",
    "@tj": "text-justify",
    "@tov": "text-overflow",
    "@tsho": "text-shadow",
    "@tovm": "text-overflow-mode",
    "@tovp": "text-overflow-position",
    "@tovc": "text-overflow-clip",
    "@tovs": "text-overflow-style",
    "@wkit": "-webkit-transition",
    "@wkitn": "-webkit-transition-name",
    "@wkitd": "-webkit-transition-duration",
    "@wkitf": "-webkit-transition-function",
    "@wkitdly": "-webkit-transition-delay",
    "@wkitic": "-webkit-transition-iteration-count",
    "@wkitdir": "-webkit-transition-direction",
    "@wkitfd": "-webkit-transition-fill-mode",
    "@wkitps": "-webkit-transition-play-state",
    "@wkitb": "-webkit-transform",
    "@wkitbo": "-webkit-transform-origin",
    "@wkitbx": "-webkit-transform-box",
    "@wkitper": "-webkit-perspective",
    "@wkitpero": "-webkit-perspective-origin",
    "@wkitbkf": "-webkit-backface-visibility",
    "@wkitap": "-webkit-appearance",
}

pd_shorthand_properties = {
    "@w100": "width: 100%",  # xshorthands start
    "@w90": "width: 90%",
    "@w80": "width: 80%",
    "@w70": "width: 70%",
    "@w60": "width: 60%",
    "@w50": "width: 50%",
    "@w40": "width: 40%",
    "@w30": "width: 30%",
    "@w20": "width: 20%",
    "@w10": "width: 10%",
    "@w33": "width: 33.3333333333%",
    "@w25": "width: 25%",
    "@w16": "width: 16.6666666667%",
    "@w5": "width: 5%",
    "@h100": "height: 100%",
    "@h90": "height: 90%",
    "@h80": "height: 80%",
    "@h70": "height: 70%",
    "@h60": "height: 60%",
    "@h50": "height: 50%",
    "@h40": "height: 40%",
    "@h30": "height: 30%",
    "@h20": "height: 20%",
    "@h10": "height: 10%",
    "@h33": "height: 33.3333333333%",
    "@h25": "height: 25%",
    "@h16": "height: 16.6666666667%",
    "@h5": "height: 5%",
    "@fs12": "font-size: 12px",
    "@fs16": "font-size: 16px",
    "@fs20": "font-size: 20px",
    "@fs24": "font-size: 24px",
    "@fs28": "font-size: 28px",
    "@fs32": "font-size: 32px",
    "@fs36": "font-size: 36px",
    "@fs40": "font-size: 40px",
    "@fs44": "font-size: 44px",
    "@fs48": "font-size: 48px",
    "@fs52": "font-size: 52px",
    "@fs56": "font-size: 56px",
    "@fs60": "font-size: 60px",
    "@fs64": "font-size: 64px",
    "@fs68": "font-size: 68px",
    "@fs72": "font-size: 72px",
    "@bgcw": "background-color: #fff",
    "@bgcb": "background-color: #000",
    "@cfff": "color: #fff",
    "@c000": "color: #000",
    "@cred": "color: #ff0000",
    "@cgrn": "color: #00ff00",
    "@cblu": "color: #0000ff",
    "@cylw": "color: #ffff00",
    "@cprp": "color: #ff00ff",
    "@ccyn": "color: #00ffff",
    "@cbrw": "color: #000000",
    "@cgrb": "color: #808080",
    "@bdn": "border: none",
    "@bdt": "border-top: 1px solid",
    "@bdb": "border-bottom: 1px solid",
    "@bdl": "border-left: 1px solid",
    "@bdr": "border-right: 1px solid",
    "@bds": "border: solid",
    "@br0": "border-radius: 0",
    "@br5": "border-radius: 5px",
    "@br10": "border-radius: 10px",
    "@br15": "border-radius: 15px",
    "@br20": "border-radius: 20px",
    "@br25": "border-radius: 25px",
    "@br30": "border-radius: 30px",
    "@br35": "border-radius: 35px",
    "@br40": "border-radius: 40px",
    "@br45": "border-radius: 45px",
    "@br50": "border-radius: 50px",
    "@brc": "border-radius: 50%",
    "@bd0": "border-width: 0",
    "@bd1": "border-width: 1px",
    "@bd2": "border-width: 2px",
    "@bd3": "border-width: 3px",
    "@m0": "margin: 0",
    "@m5": "margin: 5px",
    "@m10": "margin: 10px",
    "@m15": "margin: 15px",
    "@m20": "margin: 20px",
    "@m25": "margin: 25px",
    "@m30": "margin: 30px",
    "@m35": "margin: 35px",
    "@m40": "margin: 40px",
    "@m45": "margin: 45px",
    "@m50": "margin: 50px",
    "@mt0": "margin-top: 0",
    "@mt5": "margin-top: 5px",
    "@mt10": "margin-top: 10px",
    "@mt15": "margin-top: 15px",
    "@mt20": "margin-top: 20px",
    "@mt25": "margin-top: 25px",
    "@mt30": "margin-top: 30px",
    "@mt35": "margin-top: 35px",
    "@mt40": "margin-top: 40px",
    "@mt45": "margin-top: 45px",
    "@mt50": "margin-top: 50px",
    "@mr0": "margin-right: 0",
    "@mr5": "margin-right: 5px",
    "@mr10": "margin-right: 10px",
    "@mr15": "margin-right: 15px",
    "@mr20": "margin-right: 20px",
    "@mr25": "margin-right: 25px",
    "@mr30": "margin-right: 30px",
    "@mr35": "margin-right: 35px",
    "@mr40": "margin-right: 40px",
    "@mr45": "margin-right: 45px",
    "@mr50": "margin-right: 50px",
    "@mb0": "margin-bottom: 0",
    "@mb5": "margin-bottom: 5px",
    "@mb10": "margin-bottom: 10px",
    "@mb15": "margin-bottom: 15px",
    "@mb20": "margin-bottom: 20px",
    "@mb25": "margin-bottom: 25px",
    "@mb30": "margin-bottom: 30px",
    "@mb35": "margin-bottom: 35px",
    "@mb40": "margin-bottom: 40px",
    "@mb45": "margin-bottom: 45px",
    "@mb50": "margin-bottom: 50px",
    "@ml0": "margin-left: 0",
    "@ml5": "margin-left: 5px",
    "@ml10": "margin-left: 10px",
    "@ml15": "margin-left: 15px",
    "@ml20": "margin-left: 20px",
    "@ml25": "margin-left: 25px",
    "@ml30": "margin-left: 30px",
    "@ml35": "margin-left: 35px",
    "@ml40": "margin-left: 40px",
    "@ml45": "margin-left: 45px",
    "@ml50": "margin-left: 50px",
    "@p0": "padding: 0",
    "@p5": "padding: 5px",
    "@p10": "padding: 10px",
    "@p15": "padding: 15px",
    "@p20": "padding: 20px",
    "@p25": "padding: 25px",
    "@p30": "padding: 30px",
    "@p35": "padding: 35px",
    "@p40": "padding: 40px",
    "@p45": "padding: 45px",
    "@p50": "padding: 50px",
    "@pt0": "padding-top: 0",
    "@pt5": "padding-top: 5px",
    "@pt10": "padding-top: 10px",
    "@pt15": "padding-top: 15px",
    "@pt20": "padding-top: 20px",
    "@pt25": "padding-top: 25px",
    "@pt30": "padding-top: 30px",
    "@pt35": "padding-top: 35px",
    "@pt40": "padding-top: 40px",
    "@pt45": "padding-top: 45px",
    "@pt50": "padding-top: 50px",
    "@pr0": "padding-right: 0",
    "@pr5": "padding-right: 5px",
    "@pr10": "padding-right: 10px",
    "@pr15": "padding-right: 15px",
    "@pr20": "padding-right: 20px",
    "@pr25": "padding-right: 25px",
    "@pr30": "padding-right: 30px",
    "@pr35": "padding-right: 35px",
    "@pr40": "padding-right: 40px",
    "@pr45": "padding-right: 45px",
    "@pr50": "padding-right: 50px",
    "@pb0": "padding-bottom: 0",
    "@pb5": "padding-bottom: 5px",
    "@pb10": "padding-bottom: 10px",
    "@pb15": "padding-bottom: 15px",
    "@pb20": "padding-bottom: 20px",
    "@pb25": "padding-bottom: 25px",
    "@pb30": "padding-bottom: 30px",
    "@pb35": "padding-bottom: 35px",
    "@pb40": "padding-bottom: 40px",
    "@pb45": "padding-bottom: 45px",
    "@pb50": "padding-bottom: 50px",
    "@pl0": "padding-left: 0",
    "@pl5": "padding-left: 5px",
    "@pl10": "padding-left: 10px",
    "@pl15": "padding-left: 15px",
    "@pl20": "padding-left: 20px",
    "@pl25": "padding-left: 25px",
    "@pl30": "padding-left: 30px",
    "@pl35": "padding-left: 35px",
    "@pl40": "padding-left: 40px",
    "@pl45": "padding-left: 45px",
    "@pl50": "padding-left: 50px",
    "@dib": "display: inline-block",
    "@db": "display: block",
    "@df": "display: flex",
    "@dif": "display: inline-flex",
    "@aic": "align-items: center",
    "@aib": "align-items: baseline",
    "@aie": "align-items: end",
    "@ais": "align-items: stretch",
    "@aifa": "align-items: flex-start",
    "@aife": "align-items: flex-end",
    "@jcfs": "justify-content: flex-start",
    "@jcfe": "justify-content: flex-end",
    "@jcc": "justify-content: center",
    "@jcsb": "justify-content: space-between",
    "@jcsa": "justify-content: space-around",
    "@jcse": "justify-content: space-evenly",
    "@jcb": "justify-content: baseline",
    "@jce": "justify-content: end",
    "@jcs": "justify-content: start",
    "@fw300": "font-weight: 300",
    "@fw400": "font-weight: 400",
    "@fw500": "font-weight: 500",
    "@fw600": "font-weight: 600",
    "@fw700": "font-weight: 700",
    "@fsti": "font-style: italic",
    "@tdn": "text-decoration: none",
    "@tdu": "text-decoration: underline",
    "@lh1": "line-height: 1",
    "@lh15": "line-height: 1.5",
    "@lh2": "line-height: 2",
    "@tdc": "text-decoration: capitalize",
    "@tdl": "text-decoration: line-through",
    "@tdo": "text-decoration: overline",
    "@tdi": "text-decoration: inherit",
    "@tds": "text-decoration: solid",
    "@tdw": "text-decoration: wavy",
    "@tddb": "text-decoration: double",
    "@tdot": "text-decoration: dotted",
}
